### PR TITLE
Refresh after loading file; Model/Editor renamings

### PR DESCRIPTION
**Pull request by joshuahhh**
Bug: after loading a file with the "Load" menu option, you have to move the mouse or do something like that to get the view to update. (This doesn't sound like a big deal, but it confused me into thinking Apparatus had really long load times for a while.)

To make the logic around this stuff a bit clearer, I renamed some methods in `Model/Editor`. Lmk if you have any ideas for improvements. (`loadJsonStringIntoProjectFromExternalSource` isn't great.)

(I'll update #38 if this is OK.)

### CODE REVIEW

**Comment by electronicwhisper** [comment]
Also sometimes it seems like loading just doesn't work. You load a file, nothing happens, and so then you have to load it again. Maybe something weird with the callback timing? Maybe it loads but then a checkpoint overwrites what loaded? (This is all with the old way, I haven't tried this PR...)

**Comment by joshuahhh** [comment]
I've had that issue too. I don't see any reason why this PR should fix that, but I just went around loading a lot of files and everything seemed to work OK. So maybe we got lucky. Not sure though. We should definitely keep tracking that problem.

Do you have any thoughts on this PR?

**Comment by electronicwhisper** [comment]
Does the logic change or is it just a refactor?

One thing to be careful of is not breaking undo/redo. Like if you undo, you have to load in the previous state but then you also have to _not_ checkpoint, so that you can redo.

Undo/redo is currently a little unreliable. Like it sometimes loses your redo stack in my experience. My guess is this has to do with timing, see the `shouldCheckpoint` stuff in `index.coffee`.

**Comment by joshuahhh** [comment]
There is a logic change, designed to fix the bug I mentioned.

**Before:** After loading the deserialized JSON into `@project`, `loadFromURL` did

```
@checkpoint()
Apparatus.refresh()
```

But `loadFromFile` didn't do this. It just populated `@project`, which wasn't enough to cause a refresh (or checkpoint, for that matter).

**After:** Now both of these methods checkpoint & refresh. Or rather, the shared process was put into `loadJsonStringIntoProjectFromExternalSource`. This is supposed to mean "load a JSON string into the project, and do so in a this-is-a-new-user-action,-not-a-undo-or-redo sort of way". `undo` and `redo` still call `loadJsonStringIntoProject`, which does nothing but modify `@project`.

Which brings up a good question! Why don't undo and redo need calls to `Apparatus.refresh()`? Empirically it seems that they don't, but I don't know why.

**Comment by electronicwhisper** [comment]
They don't need calls to `Apparatus.refresh()` because they get executed within a `click` event. So the click event triggers the undo/redo to happen, but it also triggers a `refresh` just by nature of being a click event (see `index.coffee`). My refresh strategy is just to refresh (on next frame) on every possible mouse/keyboard event, so only events that I can't listen for ahead of time need to call `Apparatus.refresh()`. (If this is crazy I'm open to other suggestions, but it's worked well for development so far.)

**Comment by electronicwhisper** [comment]
This PR looks good.

**Pull request merged**
