### PR TITLE
Add Firebase-backed 'Share' button

### PR DESCRIPTION
**Pull request by joshuahhh**
This is really skeletal right now. Here's how it works:
- **Writing:** If you press the "Share" button, you are asked to login with Google. If this is successful, the drawing is uploaded to Firebase and a modal pops up with a link to copy.
  - I could remove the Google-login step, but I was worried about abuse if we had a totally open system. This puts a tiny bit of accountability in – we can ban accounts if they spam the database.
  - The login token is saved in the browser and lasts as long as we want it to. I put down two weeks.
  - The link-copying modal is really janky.
- **Reading:** The link you get looks like `http://aprt.us/editor/?loadFirebase=-K4vibVnZIyndlfTFzfl`. This acts just like `http://aprt.us/editor/?load=doc/examples/Bezier.json`. It doesn't take any auth.
  - There's no good UI for error-reporting here, but the code paths are in place.

My hope is that this is a big improvement on the existing JSON-attachment communications flow.

### CODE REVIEW

**Comment by joshuahhh** [comment]
@electronicwhisper: I fixed this to reflect the changes from #40. PTAL!

**Comment by electronicwhisper** [comment]
I think this is a good approach. I've been kind of scared of implementing this sharing feature, because it means to some level taking on the responsibility for hosting these diagrams and ensuring that these URLs work into the future. I had considered options such as hosting them as Github gists (the way bl.ocks does it), or some other way to minimize or offload this data hosting responsibility.

But I think this is a good way to do it for now. I like that we have the Google auth for now, because it ensures there is an email address associated with diagrams. This way, if we decide to change our system for hosting (either towards more minimal like gists or more maximal like accounts and a community gallery etc) then we can email folks and let them know what's happening. (This way of doing it with Firebase saves people's email addresses, I assume?)

The code looks good. Obviously yes, the modal is janky, but it's fine for this pass.

**Comment by joshuahhh** [comment]
I like your email-tracking thoughts. Right now, all that we're storing is a numeric user-ID, no email or other metadata. I will add storage of that other stuff, though AFAIK I won't be able to ensure that the email addresses being written are legitimate.

_Background on that last caveat:_ The Firebase system is pretty weird. Clients make requests to read/write nodes on the tree directly; you can't define higher-level API actions than that. But you can define authorization rules to say under what conditions a read/write should be allowed, and there's an authentication system running in parallel to this which your rules can tap into. You can say, for instance, that a user should only be able to read or write an object if it has been tagged with their logged-in UID, which makes an effective access-control system.

So here's what I'll do:
- I'll add a second "users" node to augment the existing "drawings" node.
- I'll add rules to say that you can only write to your own "user" node, and you can't make a "drawing" node until you've made a "user" node to accompany it.

But for some reason, though Firebase gives my authorization rules access to the user's logged-in UID, it doesn't give my authorization rules access to other information about the user's logged-in account, like email address. I have access to that on the client, so the client can just send it along, but I have no way of confirming in the authorization rules that it's not just totally made-up.

Problems:
- A user can make an account with a fictitious email address, and spam us with drawings. We will be able to ban the UID, but won't be able to track down who they are.
- For who-knows-what reason, a user can make an account with a fictitious email address, and then use the system as intended. We will not be able to contact them if we migrate the database. Kind of their own fault for messing with the system, though.
- A user can make an account with an email address of someone else. Then, if we migrate the database, we might spam them inappropriately. Only once, though.

I am comfortable with these problems, especially since this is a temporary system.

**Comment by electronicwhisper** [comment]
Okay sounds good

**Comment by joshuahhh** [comment]
@electronicwhisper I executed the plan I mentioned earlier. PTAL.

**Comment by electronicwhisper** [comment]
Cool.

I tried testing this but ran into trouble. I checked it out and did `npm install` and got it to build. Then it choked on whatever was in my current localStorage. This could be unrelated, I had just been using your anchor point PR. Anyway, [here](https://gist.github.com/electronicwhisper/9380e0416978d95e7450) is the contents of my `localStorage.apparatus`.

So I cleared localStorage and it worked. But when I hit the Share button it gave me this error:

```
firebase-web.js:142 Uncaught Error: There are no login transports available for the requested method.
```

But I was running it locally from `file://`. Once I had it running on a server the share button worked fine and the saved thing loaded when I put in the `loadFirebase=...` part.

Anyway, this looks good. Maybe, and this is probably unrelated, we should do some sort of try/catch to catch malformed localStorage and reset appropriately.

Once this is in, and whatever other PRs you want to merge in, we should probably "call it a version" and push it to the main site.

**Pull request merged**
