### PR TITLE
Keyboard shortcuts for menu bar buttons

### PR DESCRIPTION
**Pull request by david-crespo**
I believe `ctrl+y` is standard for redo on Windows.

I've been reading through all the code and it is just gorgeous.

### CODE REVIEW

**Comment by david-crespo** [comment]
It would probably make sense to add shortcuts for everything else in the menu bar.

**Comment by david-crespo** [comment]
Seems like you can't override cmd+n in Chrome.

I tried to pull out the shortcuts and actions into an object like 

``` coffeescript
shortcuts = {
  "command+z, ctrl+z": @_undo
  "command+shift+z, ctrl+y": @_redo
}
```

and loop through that, but for some reason it didn't work.

**Comment by electronicwhisper** [comment]
Thanks David! For the compliment and the contribution.

Your loop through an object may be not working due to the coffeescript/javascript issue that for loops do not "close" over the iterated variables. I get bitten by this all the time. For example, if you do:

```
shortcuts = {
  "command+z, ctrl+z": @_undo
  "command+shift+z, ctrl+y": @_redo
}

for own keyCombo, action of shortcuts
  key keyCombo, (e) =>
    return if Util.textFocus()
    e.preventDefault()
    action()
```

Then this will make all the key combos do `_redo` instead of what they're supposed to! This is because there is just one `action` variable that gets set as the loop iterates and the last thing it gets set to is `_redo`.

Check out the last paragraph of the [Coffeescript docs on loops](http://coffeescript.org/#loops).

The solution to that problem is to include an extra function wrapper to close over the action variable. For example, you could do:

```
shortcuts = {
  "command+z, ctrl+z": @_undo
  "command+shift+z, ctrl+y": @_redo
}

for own keyCombo, action of shortcuts
  do (keyCombo, action) =>
    key keyCombo, (e) =>
      return if Util.textFocus()
      e.preventDefault()
      action()
```

Another option is to use an iteration method that takes a callback, like `_.each`. The callback will then close over the iterated variable.

Other things:

You only need to include the `return if Util.textFocus()` line for the backspace one. This is to check that the focus is not on a text field, in which case backspace should backspace a letter, not delete the selected shape.

Do you need to have `e.preventDefault()`? I am not sure, maybe you can check this. I guess it's safer to have it so the browser doesn't try to do its own thing when you do a key combo?

Unfortunately even after removing the `return if Util.textFocus()` line, cmd+z doesn't work while the text is in codemirror. This is because codemirror traps the cmd+z. I'm sure there is a way to disable this in the [codemirror keymap](http://codemirror.net/doc/manual.html#keymaps) but I haven't figured it out yet.

Anyway, this is good enough for now. I will merge it in! :+1:

**Comment by david-crespo** [comment]
Thanks for the explanation and the merge.

I figured the `preventDefault` would be necessary to block default browser behaviors, but I didn't test without it. As for leaving in `Util.textFocus()`, that was intentional: I thought it might be strange for the keyboard shortcuts to work while typing. On the same note, I don't think it's a problem that Codemirror captures cmd+z.

**Pull request closed without merging**
